// Bancos brasileiros com cores e ícones oficiais
export const BANKS = [
  // NEOBANKS / DIGITAIS
  {
    id: 'nubank',
    name: 'Nubank',
    color: '#8A05BE',
    icon: 'card',
    type: 'digital',
    popular: true,
  },
  {
    id: 'inter',
    name: 'Banco Inter',
    color: '#FF7A00',
    icon: 'card',
    type: 'digital',
    popular: true,
  },
  {
    id: 'c6',
    name: 'C6 Bank',
    color: '#1A1F71',
    icon: 'card',
    type: 'digital',
    popular: true,
  },
  {
    id: 'next',
    name: 'Next',
    color: '#00FF00',
    icon: 'card',
    type: 'digital',
    popular: false,
  },
  {
    id: 'neon',
    name: 'Neon',
    color: '#00DDE6',
    icon: 'card',
    type: 'digital',
    popular: false,
  },
  {
    id: 'picpay',
    name: 'PicPay',
    color: '#21C25E',
    icon: 'card',
    type: 'digital',
    popular: true,
  },
  {
    id: 'will',
    name: 'Will Bank',
    color: '#FF6B00',
    icon: 'card',
    type: 'digital',
    popular: false,
  },
  {
    id: 'digio',
    name: 'Digio',
    color: '#00B0F0',
    icon: 'card',
    type: 'digital',
    popular: false,
  },
  {
    id: 'original',
    name: 'Banco Original',
    color: '#00A651',
    icon: 'card',
    type: 'digital',
    popular: false,
  },
  {
    id: 'banqi',
    name: 'Banqi',
    color: '#FF6B00',
    icon: 'card',
    type: 'digital',
    popular: false,
  },

  // BANCOS TRADICIONAIS
  {
    id: 'itau',
    name: 'Itaú',
    color: '#EC7000',
    icon: 'business',
    type: 'tradicional',
    popular: true,
  },
  {
    id: 'bradesco',
    name: 'Bradesco',
    color: '#CC092F',
    icon: 'business',
    type: 'tradicional',
    popular: true,
  },
  {
    id: 'santander',
    name: 'Santander',
    color: '#EC0000',
    icon: 'business',
    type: 'tradicional',
    popular: true,
  },
  {
    id: 'bb',
    name: 'Banco do Brasil',
    color: '#003DA5',
    icon: 'business',
    type: 'tradicional',
    popular: true,
  },
  {
    id: 'caixa',
    name: 'Caixa Econômica',
    color: '#005CA9',
    icon: 'business',
    type: 'tradicional',
    popular: true,
  },
  {
    id: 'safra',
    name: 'Safra',
    color: '#1A3C6E',
    icon: 'business',
    type: 'tradicional',
    popular: false,
  },
  {
    id: 'pan',
    name: 'Banco Pan',
    color: '#00A0E3',
    icon: 'business',
    type: 'tradicional',
    popular: false,
  },
  {
    id: 'citibank',
    name: 'Citibank',
    color: '#003B70',
    icon: 'business',
    type: 'tradicional',
    popular: false,
  },
  {
    id: 'hsbc',
    name: 'HSBC',
    color: '#DB0011',
    icon: 'business',
    type: 'tradicional',
    popular: false,
  },

  // CARTÕES DE CRÉDITO
  {
    id: 'americanexpress',
    name: 'American Express',
    color: '#006FCF',
    icon: 'card',
    type: 'cartao',
    popular: true,
  },
  {
    id: 'hipercard',
    name: 'Hipercard',
    color: '#D12027',
    icon: 'card',
    type: 'cartao',
    popular: false,
  },
  {
    id: 'aura',
    name: 'Aura',
    color: '#00A0E3',
    icon: 'card',
    type: 'cartao',
    popular: false,
  },

  // OUTROS / FINTECHS
  {
    id: 'mercadopago',
    name: 'Mercado Pago',
    color: '#00ADEF',
    icon: 'wallet',
    type: 'fintech',
    popular: true,
  },
  {
    id: 'pagseguro',
    name: 'PagBank',
    color: '#96C22F',
    icon: 'wallet',
    type: 'fintech',
    popular: true,
  },
  {
    id: 'stone',
    name: 'Stone',
    color: '#00A0E3',
    icon: 'wallet',
    type: 'fintech',
    popular: false,
  },
  {
    id: 'cielo',
    name: 'Cielo',
    color: '#003A70',
    icon: 'wallet',
    type: 'fintech',
    popular: false,
  },
  {
    id: 'rede',
    name: 'Rede',
    color: '#E31837',
    icon: 'wallet',
    type: 'fintech',
    popular: false,
  },
  {
    id: 'ame',
    name: 'Ame Digital',
    color: '#FF6B00',
    icon: 'wallet',
    type: 'fintech',
    popular: false,
  },
  {
    id: 'recarga',
    name: 'RecargaPay',
    color: '#00A0E3',
    icon: 'wallet',
    type: 'fintech',
    popular: false,
  },

  // OUTROS
  {
    id: 'outro',
    name: 'Outro Banco',
    color: '#666666',
    icon: 'card',
    type: 'outro',
    popular: false,
  },
];

export const getBankById = (id) => BANKS.find(b => b.id === id) || BANKS[BANKS.length - 1];

export const getPopularBanks = () => BANKS.filter(b => b.popular);

export const getBanksByType = (type) => BANKS.filter(b => b.type === type);

export const BANK_TYPES = [
  { id: 'all', name: 'Todos' },
  { id: 'digital', name: 'Digital' },
  { id: 'tradicional', name: 'Tradicional' },
  { id: 'cartao', name: 'Cartão' },
  { id: 'fintech', name: 'Fintech' },
];
